import { __sS } from "./sydneyDom_v3.js";

//abstract styles
__sS([
    {
        nameTag:"outline",
        style:{outline:"2px dashed #fff"}
    },
    {
        nameTag:"no-txt",
        style:{
            pointerEvents:"none"
        }
    },
    {
        nameTag:"thinBorder",
        style:{
            border:"1px solid rgba(255,255,255,.1)"
        }
    },
    {
        nameTag:"br-1",
        style:{
            borderRadius:"1rem"
        }
    },
    {
        nameTag:"br-.5",
        style:{
            borderRadius:".5rem"
        }
    },
    {
        nameTag:"row-start",
        style:{
            display:"flex",
            flexDirection:"row",
            alignItems:"center"
        }
    },
        {
        nameTag:"row-space",
        style:{
            display:"flex",
            flexDirection:"row",
            justifyContent:"space-around"
        }
    },
    {
        nameTag:"row-center",
        style:{
            display:"flex",
            flexDirection:"row",
            alignItems:"center",
            justifyContent:"center"
        }
    },
        {
        nameTag:"col-start",
        style:{
            display:"flex",
            flexDirection:"column",
            alignItems:"flex-start"
        }
    },
    {
        nameTag:"col-center",
        style:{
            display:"flex",
            flexDirection:"column",
            alignItems:"center",
        }
    },
    {
        nameTag:"h-txt",
        style:{
            textTransform:"capitalize",
            fontFamily:"h-txt",
            fontWeight:"700"
        }
    },
    {
        nameTag:"n-txt",
        style:{
            textTransform:"capitalize",
            fontFamily:"h-txt",
            fontWeight:"400",
            minWidth:"max-content"
        }
    },
    {
        nameTag:"n-icon",
        style:{
            height:"18px",
            width:"18px",
            minHeight:"18px",
            minWidth:"18px",
            cursor:"pointer"
        }
    },
    {
        nameTag:"n2-icon",
        style:{
            height:"25px",
            width:"25px",
            cursor:"pointer"
        }
    },
    {
        nameTag:"copy-txt",
        style:{
            cursor:"pointer"
        }
    },
    {
        nameTag:"comic_lines",
        style:{
            border:"5px solid #F3BA2F"
        }
    },
    {
        nameTag:"comic_outline",
        style:{
            outline:"3px solid #000000"
        }
    }
])
//abstract styles